https://engcourses-uofa.ca/books/introduction-to-solid-mechanics/linear-algebra/2-2-linear-maps-between-vector-spaces/examples-and-problems/

2.2.6.1

In [1]:
import numpy as np
from numpy.linalg import *
from scipy.linalg import *
M = np.array([[1, 1, 0], [1, 1, 0], [0, 0, 1]])
print("M^T=\n",M.transpose()) # transpose matrix
print("Det (M) =",det(M)) # determinant
print("Vectors in the Kernel (Nullspace)=\n",null_space(M)) # null space unit matrix
eigen = eig(M) # eigen values and vectors
print("eigenvectors and eigenvalues\n",eigen)
# first index is eigen values
print("Eigenvalues = \n",eigen[0])
# Columns are normalized eigenvectors. Transpose is used to convert them into rows
print("Eigenvectors = \n",eigen[1].T)
#The rotation matrix is made out of the rows of the eigenvectors
Q=eigen[1].T
print("Q =\n",Q)
# @ is matrix multiply
print("Q.M.Q^T=\n",Q@M@Q.transpose())
# this also works
print("Q.M.Q^T=\n",Q.dot(M).dot(Q.transpose()))

M^T=
 [[1 1 0]
 [1 1 0]
 [0 0 1]]
Det (M) = 0.0
Vectors in the Kernel (Nullspace)=
 [[ 0.70710678]
 [-0.70710678]
 [-0.        ]]
eigenvectors and eigenvalues
 (array([2.+0.j, 0.+0.j, 1.+0.j]), array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]]))
Eigenvalues = 
 [2.+0.j 0.+0.j 1.+0.j]
Eigenvectors = 
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Q =
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Q.M.Q^T=
 [[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
Q.M.Q^T=
 [[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


2.2.6.2

In [2]:
import numpy as np
import numpy as np
from numpy.linalg import *
x = np.array([1, 1, 1]) 
M = np.array([[2, 1, 0], [1, 5, 2], [2, -1, 3]])
# matrix multiply
y = np.matmul(M,x)
# same operation
y = M@x
print(y)
u = np.array([3/5, 4/5, 0])
v = np.array([-4/5, 3/5, 0])
w = np.array([0, 0, 1])
print("Check length of vectors")
print("|u|=",norm(u))
print("|v|=",norm(v))
print("|w|=",norm(w))
# @ also works as dot product
print("Check orthogonality")
print("u.v =",u@v)
print("u.w =",u@w)
print("v.w =",v@w)
print("Check orientation")
print("u.v\u00D7w=",u@np.cross(v,w))
# Q will be a 3 x 3
Q = u
# Adds row to matrix
Q = np.vstack([Q, v])
Q = np.vstack([Q, w])
print("Q=\n",Q)
#Alternatively, Q can be defined as:
Q=np.array([u,v,w])
print("Q=\n",Q)
print("x=\n",x)
xp = Q@x
yp = Q@y
Mp = Q@M@Q.transpose()
print("x'=\n",xp)
print("y=\n",y)
print("M=\n",M)
print("M'=\n",Mp)
print("y'=M'x'=\n",Mp@xp)
print("y'= Qy\n",yp)

[3 8 4]
Check length of vectors
|u|= 1.0
|v|= 1.0
|w|= 1.0
Check orthogonality
u.v = 0.0
u.w = 0.0
v.w = 0.0
Check orientation
u.v×w= 1.0
Q=
 [[ 0.6  0.8  0. ]
 [-0.8  0.6  0. ]
 [ 0.   0.   1. ]]
Q=
 [[ 0.6  0.8  0. ]
 [-0.8  0.6  0. ]
 [ 0.   0.   1. ]]
x=
 [1 1 1]
x'=
 [ 1.4 -0.2  1. ]
y=
 [3 8 4]
M=
 [[ 2  1  0]
 [ 1  5  2]
 [ 2 -1  3]]
M'=
 [[ 4.88  1.16  1.6 ]
 [ 1.16  2.12  1.2 ]
 [ 0.4  -2.2   3.  ]]
y'=M'x'=
 [8.2 2.4 4. ]
y'= Qy
 [8.2 2.4 4. ]


2.2.6.3

In [3]:
import numpy as np
from numpy.linalg import *
# input degrees get radians
theta = np.radians(20) 
c, s = np.cos(theta), np.sin(theta)
# using the 2D rotation formula
Q = np.array([[c, -s], [s, c]]) 
print("Q =\n",Q)
u = np.array([2, 2])
v = Q@u
print("v =",v)
print("|u| =",norm(u))
print("|v| =",norm(v))
# using angle formula
th=np.arccos(u@v/norm(u)/norm(v))
print("theta(rad) =",th) 

Q =
 [[ 0.93969262 -0.34202014]
 [ 0.34202014  0.93969262]]
v = [1.19534495 2.56342553]
|u| = 2.8284271247461903
|v| = 2.8284271247461903
theta(rad) = 0.3490658503988661
